(add-to-list 'load-path "~/.emacs.d/")
(setq custom-file "~/.emacs.d/custom.el")
(require 'cl)

(setenv "PATH" (concat "/usr/local/bin:" (getenv "PATH")))
(setq exec-path (append exec-path '("/usr/local/bin")))

(require 'marmalade)
(require 'my-packages)
(require 'nginx-mode)
(require 'project-mode)
(require 'campfire)
(require 'rvm)
(require 'rspec-mode)
(require 'ruby-tools)
(require 'slim-mode)
(require 'yaml-mode)
(require 'auto-complete-config)
(require 'workgroups)
(require 'sr-speedbar)
(require 'key-bindings)
(require 'duplicate-line)
(require 'brightscript-mode)
(require 'linum-off)
(require 'auto-modes-list)
(require 'hooks)
(require 'defaults)
(require 'global-modes)

(load custom-file 'noerror)
(load-theme 'zen-and-art)


